###This file is generated by AI from prompts/src/main.py. DO NOT MODIFY THIS FILE MANUALLY###

from ai_coder.llm_client import call_llm
import requests
import textwrap

discord_webhook = "https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN"


def article_summary(url: str) -> str:
    """
    Fetches a webpage and uses call_llm to get the summary of the webpage.
    :param url: URL of the webpage to summarize.
    :return: Summary of the webpage.
    """
    response = requests.get(url)
    webpage_content = response.text
    summary = call_llm(webpage_content, sys_prompt="Summarize this webpage content:")
    return summary


def send_discord(message: str) -> None:
    payload = {"content": message}
    response = requests.post(discord_webhook, json=payload)
    if response.status_code == 204:
        print("Message sent successfully")
    else:
        print(f"Failed to send message: {response.status_code}")


def split_messages_to_send(message, delimiter="\n") -> None:
    messages = message.split(delimiter)
    for msg in messages:
        wrapped_messages = textwrap.wrap(msg, 2000, replace_whitespace=False)
        for wrapped_msg in wrapped_messages:
            send_discord(wrapped_msg)


if __name__ == "__main__":
    print(
        article_summary(
            "https://techcrunch.com/2024/03/27/amazon-doubles-down-on-anthropic-completing-its-planned-4b-investment/"
        )
    )
