###This file is generated by AI from prompts/src/main.py. DO NOT MODIFY THIS FILE MANUALLY###

import requests
from bs4 import BeautifulSoup
from ai_coder.openai_client import call_llm

discord_webhook = 'https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN'


def article_summary(url: str) ->str:
    """
Function to fetch a webpage and get its summary using call_llm function
:param url: string, url of the webpage
"""
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    webpage_text = ''.join(soup.stripped_strings)
    summary = call_llm(webpage_text)
    return summary


def send_discord(message: str) ->None:
    """
Function to send a message to a Discord webhook
:param message: string, the message to send
"""
    requests.post(discord_webhook, data={'content': message})


def split_messages_to_send(message, delimiter='\n') ->None:
    """
Function to split a long message into chunks of 2000 characters and send it to Discord
:param message: string, the message to send to discord
:param delimiter: string, the delimiter to split the message

Rules: 
1. The message is a long string that has bullet points and delimited by "delimiter".
2. The message should be split by 2000 characters and send to discord.
3. The message send to discord should be sub group of the original message, which is split by "delimiter", and has a maximum length of 2000 characters.

To send to discord you can call {send_discord} function.
"""
    chunks = [message[i:i + 2000] for i in range(0, len(message), 2000)]
    for chunk in chunks:
        messages = chunk.split(delimiter)
        for msg in messages:
            send_discord(msg)


if __name__ == '__main__':
    print(article_summary(
        'https://techcrunch.com/2024/03/27/amazon-doubles-down-on-anthropic-completing-its-planned-4b-investment/'
        ))
