###This file is generated by AI from prompts/src/main.py. DO NOT MODIFY THIS FILE MANUALLY###

import requests

discord_webhook = "https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN"


def article_summary(url: str) -> str:
    response = requests.get(url)
    webpage = response.text
    return webpage


def send_discord(message: str) -> None:
    payload = {"content": message}
    response = requests.post(discord_webhook, json=payload)
    if response.status_code != 204:
        print("Failed to send message to Discord webhook")


def split_messages_to_send(message, delimiter="\n") -> None:
    message_parts = message.split(delimiter)
    for part in message_parts:
        send_discord(part)


if __name__ == "__main__":
    print(
        article_summary(
            "https://techcrunch.com/2024/03/27/amazon-doubles-down-on-anthropic-completing-its-planned-4b-investment/"
        )
    )
