###This file is generated by AI from prompts/src/main.py. DO NOT MODIFY THIS FILE MANUALLY###

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel


class Item(BaseModel):
    a: float
    b: float


app = FastAPI()


@app.post("/add/")
def add(item: Item) -> float:
    return item.a + item.b


@app.post("/sub/")
def sub(item: Item) -> float:
    return item.a - item.b


@app.post("/multiply/")
def multiply(item: Item) -> float:
    return item.a * item.b


@app.post("/divide/")
def divide(item: Item) -> float:
    if item.b == 0:
        raise HTTPException(status_code=400, detail="Cannot divide by zero")
    return item.a / item.b


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8000)
