###This file is generated by AI from prompts/src/main.py. DO NOT MODIFY THIS FILE MANUALLY###

import requests
from bs4 import BeautifulSoup
from ai_coder.llm_client import call_llm

discord_webhook = "https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN"


class AINews:

    def __init__(self):
        pass

    def article_summary(self, url: str) -> str:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        text = " ".join(p.get_text() for p in soup.find_all("p"))
        summary = call_llm(text)
        return summary

    def send_discord(self, message: str) -> None:
        payload = {"content": message}
        response = requests.post(discord_webhook, json=payload)
        response.raise_for_status()

    def split_messages_to_send(self, message, delimiter="\n") -> None:
        messages = message.split(delimiter)
        buffer = ""
        for part in messages:
            if len(buffer) + len(part) + len(delimiter) > 2000:
                self.send_discord(buffer)
                buffer = part + delimiter
            else:
                buffer += part + delimiter
        if buffer:
            self.send_discord(buffer)


if __name__ == "__main__":
    ainews = AINews()
    print(
        ainews.article_summary(
            "https://techcrunch.com/2024/03/27/amazon-doubles-down-on-anthropic-completing-its-planned-4b-investment/"
        )
    )
